# Core Paths
EINK_RENDERER_PATH="/home/pi/git/projects/url-image-to-eink/url_jpg_to_eink.py"
OUTPUT_FILE_PATH="/home/pi/projects/display-on-eink-random-photo/output.bmp"

# Photo Mode Settings
PYTHON_FETCHER_PATH="/home/pi/projects/multi-provider-url-image-fetcher2/fetch_photo_url.py"
PROVIDERS_CONFIG_PATH="/home/pi/projects/multi-provider-url-image-fetcher2/providers.json"
DEFAULT_SEARCH_QUERY="street photography"

# Info Mode Settings
PYTHON_API_RENDERER_PATH="/home/pi/git/projects/eink-api-renderer/generate_eink_image_from_api.py"
PRESETS_CONFIG_PATH="/home/pi/git/projects/eink-api-renderer/presets.json"
PRESETS="wiki_en_tfa wiki_en_onthisday wiki_en_news wiki_en_dyk wiki_es_onthisday wiki_es_random random_joke tech_joke_two_part stoic_quote zen_quote open_trivia fact_facts meow_facts useless_facts daily_advice"

# Display Parameters
DISPLAY_WIDTH=800
DISPLAY_HEIGHT=480
LOG_LEVEL=INFO
