# Path configuration for Python executable script
PYTHON_API_RENDERER_PATH="/home/pi/git/projects/eink-api-renderer/generate_eink_image_from_api.py"
PRESETS_CONFIG_PATH="/home/pi/git/projects/eink-api-renderer/presets.json"
EINK_RENDERER_PATH="/home/pi/git/projects/url-image-to-eink/url_jpg_to_eink.py"

# Absolute path for the rendered target image
OUTPUT_FILE_PATH="/home/pi/git/projects/eink-api-renderer/output.bmp"

# Default execution settings
LOG_LEVEL="INFO"
